---
all:
  children:
    zabbix_proxy:
      hosts:
        zabbix-proxy-01:
          ansible_host: 192.168.19.5
          ansible_user: ansible
      vars:
        # Choose database type: sqlite or mysql
        zabbix_db_type: sqlite
        # MySQL specific variables (only used if zabbix_db_type: mysql)
        # zabbix_db_user: zabbix
        # zabbix_db_password: your_password
        # zabbix_db_name: zabbix_proxy
        # zabbix_db_host: localhost
