---
- name: Create post-deployment VM snapshot
  community.general.proxmox_snap:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    vmid: "{{ item.1.vmid_cloned }}"
    snapname: "{{ snapshot_name | default('snapshot-' + lookup('pipe', 'date +%Y-%m-%d')) }}"
    description: "Snapshot created by Ansible after deployment"
    state: present
  loop: "{{ vm_templates | subelements('vms') }}"
  delegate_to: localhost
