---
- name: Clone VMs
  community.general.proxmox_kvm:
    node: "{{ proxmox_node }}"
    vmid: "{{ item.1.vmid }}"
    clone: "{{ item.0.template }}"
    name: "{{ item.1.name }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_host }}"
    storage: "vm-nvme1"
    state: present
    timeout: 600
  loop: "{{ vm_templates | subelements('vms') }}"

- name: Configure Cloud-Init
  community.general.proxmox_kvm:
    node: "{{ proxmox_node }}"
    name: "{{ item.1.name }}"
    vmid: "{{ item.1.vmid_cloned }}"
    update: true
    cores: "{{ item.1.cpu }}"
    memory: "{{ item.1.ram }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_host }}"
    ipconfig:
      ipconfig0: "ip={{ item.1.network.ip }},gw={{ item.1.network.gateway }}"
    nameservers: "{{ item.1.network.dns_servers }}"
  loop: "{{ vm_templates | subelements('vms') }}"

- name: Start VMs
  community.general.proxmox_kvm:
    node: "{{ proxmox_node }}"
    vmid: "{{ item.1.vmid_cloned }}"
    name: "{{ item.1.name }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_host }}"
    state: started
  loop: "{{ vm_templates | subelements('vms') }}"
