---
- name: Clone VM from template
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ item.1.vmid }}"
    newid: "{{ item.1.vmid_cloned }}"
    clone: "{{ item.0.template }}"
    name: "{{ item.1.name }}"
    storage: "{{ proxmox_storage }}"
    state: present
    timeout: 600
  loop: "{{ vm_templates | subelements('vms') }}"
  delegate_to: localhost

- name: Resize primary disk to requested size
  community.general.proxmox_disk:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    vmid: "{{ item.1.vmid_cloned }}"
    disk: virtio0
    size: "{{ disk_size_gb }}G"
    state: resized
  loop: "{{ vm_templates | subelements('vms') }}"
  delegate_to: localhost
  when: disk_size_gb is defined and disk_size_gb | int > 0

- name: Configure Cloud-Init settings
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ item.1.vmid_cloned }}"
    name: "{{ item.1.name }}"
    update: true
    cores: "{{ item.1.cpu }}"
    memory: "{{ item.1.ram }}"
    ipconfig:
      ipconfig0: "ip={{ item.1.network.ip }},gw={{ item.1.network.gateway }}"
    nameservers: "{{ item.1.network.dns_servers }}"
    searchdomains: "{{ item.1.hostname }}"
    ciuser: "{{ vm_connection_user }}"
    sshkeys: "{{ vm_connection_ssh_pubkey }}"
  loop: "{{ vm_templates | subelements('vms') }}"
  delegate_to: localhost

- name: Start VMs
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ item.1.vmid_cloned }}"
    name: "{{ item.1.name }}"
    state: started
  loop: "{{ vm_templates | subelements('vms') }}"
  delegate_to: localhost

- name: Wait for SSH to be available
  ansible.builtin.wait_for:
    port: 22
    host: "{{ item.1.network.ip.split('/')[0] }}"
    search_regex: OpenSSH
    timeout: 5
  loop: "{{ vm_templates | subelements('vms') }}"
  delegate_to: localhost
  register: ssh_check
  until: ssh_check is success
  retries: 30
  delay: 10
