---
- name: Reload PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: reloaded
  become: true

- name: Restart zabbix-server
  ansible.builtin.systemd:
    name: zabbix-server
    state: restarted
  become: true
