---
# Proxmox API Connection
proxmox_host: "10.10.10.101"
proxmox_node: "prx2"
proxmox_api_user: "root@pam"
proxmox_api_password: "IXII123!"
proxmox_storage: "vm-sata1"

# Cloud-Init / Ansible connection user
# This user is created by cloud-init and used by Ansible to connect to the VM
vm_connection_user: "ansible"
vm_connection_ssh_pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN5a4Aqkcvsmu4NQS7vj/fIRZ4E9ao8h5VUdcUaemCSU dragon@jumper"

# Admin user created by the manage_users role
linux_user: "dragon"
linux_user_password: "r"
linux_ssh_pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/pRNjhwdzA8X6Nk7KH/b4G5qHyHCCaEk0yKPO3+oFF jumper@dragon.local"

# VM Defaults
disk_size_gb: 20
